### ISSUE TITLE
Wyświetlanie zadań i odpowiedzi w jednym widoku gracza

### ISSUE THREAD

**Issue by krzysztof9nowak** [progzesp22/frontend#12]
Dodać wyświetlanie przesłanych odpowiedzi wraz z ich statusem na liście zadań dostępnych dla gracza.
![image](https://user-images.githubusercontent.com/46313284/200878244-4094b2ab-1620-4ab3-b743-5c04d7a58a58.png)

Rysunek jest bardzo poglądowy. Sprawa otwarta na dyskusje

**Comment by krzysztof9nowak** [comment]
Na razie tego nie wykonujemy

**Comment by Xgreg2001** [comment]
Duplicate of #30
