### ISSUE TITLE
Utworzenie ekranu logowania i rejestracji

### ISSUE THREAD

**Issue by krzysztof9nowak** [progzesp22/frontend#15]
Stworzyć ekrany (klasa Fragment) Logowanie i Rejestracji gier na podstawie:
https://github.com/progzesp22/docs/blob/milestone/notes.md
Stylistyka nie musi być wzorowana na innych ekranach. Jesteśmy otwarci na nowy, składny wygląd całej aplikacji.

**Comment by Sophie-1227** [comment]
@krzysztof9nowak  mam może głupie pytanie, ale jak mam zrobić binding, w obecnym stanie apki?
![image](https://user-images.githubusercontent.com/92611357/203616077-aff395e5-6e9e-458b-ae90-5718ea1889bc.png)

**Comment by krzysztof9nowak** [comment]
Możesz wrzucić to co masz na brancha? Muszę zobaczyć jak to wygląda .xml tego fragmentu, który stworzyłaś

**Comment by Sophie-1227** [comment]
Jasne, to dokończę z tłem walczyć i wrzucę
