### ISSUE TITLE
Stworzenie ekranu [Gracz] zadanie

### ISSUE THREAD

**Issue by Xgreg2001** [progzesp22/frontend#30]
https://github.com/progzesp22/docs/blob/main/milestone.md#gracz-zadanie

Do tego ekranu przechodzimy z widoku [wszystkich tasków](https://github.com/progzesp22/docs/blob/main/milestone.md#gracz-lista-zada%C5%84), Powinien on zawierać nazwę zadania, jego opis oraz typ subtasków oraz listować wcześniejsze odpowiedzi dla tego taska (jeśli takie były). Jeżeli nie ma odpowiedzi lub ostatnia odpowiedź została odrzucona powinien umożliwiać przejście do [ekranu tworzenia nowej odpowiedzi](https://github.com/progzesp22/docs/blob/main/milestone.md#gracz-odpowied%C5%BA).

**Comment by Sophie-1227** [comment]
Czy listowanie odpowiedzi innych graczy (albo subtasków) może być na nowym ekranie, a tu tylko button do przejścia? Bo tu się zrobiło mega tłoczno
