### ISSUE TITLE
Ikona aplikacji

### ISSUE THREAD

**Issue by krzysztof9nowak** [progzesp22/frontend#8]
Zaproponować kilka pomysłów ikonki aplikacji, wybrać najlepszy i narysować

**Comment by Sophie-1227** [comment]
![316588261_1249598208940640_4371838776699221584_n](https://user-images.githubusercontent.com/92611357/203424965-ed6bc2c7-d554-4165-97d0-66d32b83f69f.jpg)
![316496856_878480979821041_4590749367364827548_n](https://user-images.githubusercontent.com/92611357/203424969-2cc46fc0-4e36-495b-af81-b46c47089484.jpg)
![316366192_838073327523349_707971307149336785_n](https://user-images.githubusercontent.com/92611357/203424970-a61bb5ef-6db6-419a-9333-269a7c9b2501.jpg)
![316160775_1314383455989000_4845733022393639967_n](https://user-images.githubusercontent.com/92611357/203424971-98c67daf-f950-4966-af85-8e66df6fe98b.jpg)

**Comment by Sophie-1227** [comment]
Pozostał wybór kolorystyki. Zastanawiam się jeszcze nad jedną opcją gradientu, ale to jeszcze jest do przemyślenia i sprawdzenia ilości wolnego czasu

**Comment by Sophie-1227** [comment]
Ikona została dodana do aplikacji. Czeka na zatwierdzenie
